const endpointUrl = `https://wincacademydatabase.firebaseio.com/lars/tasks`;

/**
 * Function that makes a fetch call to the endpoint and gets all tasks that are stored there. Converts the response into json and returns json.
 */
const getAllTasks = async () => {
    try {
        const response = await fetch(`${endpointUrl}.json`, {method: 'GET'});
        const json = await response.json();
        return json;
    } catch (error) {
        console.log(error);
    }
}

/**
 * Function that posts a task object to the database
 * @param {Object} task The task object
 * @param {string} task.description the description of the task
 * @param {boolean} task.done bool that decides if the task had been completed - default: false
 */
const postTask = async (task) => {
    try {
        const post = await fetch(`${endpointUrl}.json`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(task) });
        return post;
    } catch (error) {
        console.log(error);
    }
}

/**
 * Function that deletes a task selected by its id hash
 * @param {string} hash A hash generated by firebase that serves as an id
 */
const deleteTask = async (hash) => {
    try {
        const deleteItem = await fetch(`${endpointUrl}/${hash}.json`, {method: 'DELETE'});
    } catch (error) {
        console.log(error);
    }
}

/**
 * Function that posts a task object to the database
 * @param {string} hash A hash generated by firebase that serves as an id
 * @param {Object} task The task object
 * @param {string} task.description the description of the task
 * @param {boolean} task.done bool that decides if the task had been completed - default: false
 */
const putTask = async (hash, task) => {
    try {
        const put = await fetch(`${endpointUrl}/${hash}.json`, {method: 'PUT', body: JSON.stringify(task) });
        const json = await put.json();
        return json;
    } catch (error) {
        console.log(error);
    }
}