
/**
 * Fucntion that creates a single task item
 * @param {Object} task An object that takes three properties
 * @param {string} task.id - Generated by firebase - Not needed.
 * @param {string} task.description - Description of a task.
 * @param {boolean} task.done - Bool that determines wether the task has been completed.
 */
const createTaskItem = (task) => {
    //create containing div
    const div = document.createElement('div');
    div.classList.add('task-item');

    //create checkbox
    const checkbox = document.createElement('input');
    checkbox.type = "checkbox";
    if(task.done) {
        checkbox.checked = true;
    }
    div.appendChild(checkbox);

    //create description
    const p = document.createElement('p');
    const taskdescription = document.createTextNode(task.description);
    p.appendChild(taskdescription);
    div.appendChild(p);

    //create delete button
    const deleteButton = document.createElement('button');
    deleteButton.classList.add('delete-button');
    div.appendChild(deleteButton);
    return div;
}

const taskContainer = document.querySelector('main');
/**
 * Function that adds all tasks that where recieved from the database into the dom by using the createTaskItem function
 */
const addTasksToDom = async () => {
    const tasks = await convertResponse();
    const taskItems = tasks.map(item => {
        const taskItem = createTaskItem(item);
        return taskItem;
    });
    taskItems.forEach(item => {
        taskContainer.appendChild(item);
    });
}

/**
 * Function that converts the object with hashes into an array with tasks.
 */
const convertResponse = async () => {
    const result = await getAllTasks();
    let tasks = Object.keys(result).map(key => ({
        id: key,
        description: result[key].description,
        done: result[key].done
    }));
    //console.log("After the tasks array", tasks);
    return tasks;
}

const handleNavInput = (event) => {
    const taskDescription = navTextInput.value;
    const task = {description: taskDescription, done: false};
    
}

const navTextInput = document.querySelector('nav input');
const addButton = document.getElementById('add-button');
addButton.addEventListener('click', handleNavInput)

addTasksToDom();